theme:
  colors:
    background: '#000000'
    surface: '#2E3F42FF'
    primary: '#00ffb3'
    text: '#f4f4f5'
  card:
    aspectRatio: 9/19
    borderRadius: .5rem
    borderWidth: 0px
    gap: 24px
    hoverBorderWidth: 3px
  layout:
    maxWidth: 1600px
    paddingX: 96px
    gridColumns: 4
