theme:
  colors:
    background: "#242431FF"
    surface: "#1B2021FF"
    primary: "#16909BFF"
    text: "#f4f4f5"
  card:
    aspectRatio: "9/19.5"
    borderRadius: "2rem"
    borderWidth: "2px"
    gap: "24px"
  layout:
    maxWidth: "1600px"
    paddingX: "144px"
