theme:
  colors:
    background: "#26269AFF"
    surface: "#FC1961C8
    primary: "#FFD60AFF"
    text: "#73C6AFFF"
  card:
    aspectRatio: "1/2"
    borderRadius: "1rem"
    borderWidth: "10px"
    gap: "36px"
  layout:
    maxWidth: "1600px"
    paddingX: "200px"
